categories:
        - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and install mayachemtools.
long_description: |
        The long description here ...
name: package_mayachemtools_9_0 
owner: planemo
remote_repository_url: 
type: tool_dependency_definition
