---
description:  tool provides sdf file of extracted compounds from   
long_description: |
              This is a long description..     
name: mayatool_extract 
owner: planemo 
type: unrestricted 
homepage_url: 
remote_repository_url: 
