---
description: Selects compound name or ids  of interesting molecules based on certain cutoff range. 
long_description: |
              This is a long description..     
name: candidate_compound_select
owner: anmoljh
type: unrestricted 
homepage_url: 
remote_repository_url: 
