---
description: extracts compound IDs to be used in downstream compound extraction from sdf files.
long_description: |
              This is a long description..     
name: compound_id_extract 
owner: planemo 
type: unrestricted 
homepage_url: 
remote_repository_url: 
